:PROPERTIES:
:ID:       6bef267f-b879-4c8f-bdc2-6a3546a54896
:END:
#+filetags: :数学:数理逻辑:
#+title: 逻辑语言

* 命题

语句“这里的景色非常漂亮”是主观的，取决于不同人的不同品味，你不好直接下判断说，
诶，这个语句是真的还是假的，针对理性的领域，我们需要更精确的语言，以便客观的判断，
一个语句的真假，于是，我们有了以下受限的语句的定义：

#+begin_definition
*命题（statement）*
一个命题即可以判断真假的语句，且命题只能是真或者假，不能既真又假。由于我们限制命
题可以判断真假，特别地，不存在不真不假的命题。
#+end_definition

* 命题的操作

有了命题后，我们可以定义对命题的操作。

首先是否操作：

#+begin_definition
*否命题（negation）*
任何命题 \( A \) 都存在对应的否命题 \( \neg A \)，\( \neg A \) 为真当且仅当 \( A \) 为假。
#+end_definition

我们可以把否操作表示成真值表（truth table）的形式，如下：

| 命题 | 真值1 | 真值2 |
| \( A \) | \( \mathrm{T} \) | \( \mathrm{F} \) |
| \( \neg A \) | \( \mathrm{F} \) | \( \mathrm{T} \) |

类似的，可以定义析取和合取操作，如下：

#+begin_definition
*合取（conjunction）*
给定两个命题 \( A, B \) ，合取这两个命题可得到命题 \( A \land B \)，该命题为真当且仅当 \( A, B \) 均为
真。
#+end_definition

#+begin_definition
*析取（disjunction）*
给定两个命题 \( A, B \) ，析取这两个命题可得到命题 \( A \lor B \)，该命题为真当且仅当 \( A, B \) 中其
中一个为真，这包括两个都为真的情况。
#+end_definition

这两个操作的真值表如下：

| A | B | \( A \land B \) | \( A \lor B \) |
| \( \mathrm{T} \) | \( \mathrm{T} \) | \( \mathrm{T} \) | \( \mathrm{T} \) |
| \( \mathrm{T} \) | \( \mathrm{F} \) | \( \mathrm{F} \) | \( \mathrm{T} \) |
| \( \mathrm{F} \) | \( \mathrm{T} \) | \( \mathrm{F} \) | \( \mathrm{T} \) |
| \( \mathrm{F} \) | \( \mathrm{F} \) | \( \mathrm{F} \) | \( \mathrm{F} \) |

* 谓词

命题有个缺点，就是我们无法参数化输入，举个例子， \( x > 3 \) 不是命题，这是因为不知道
\( x \) 的具体值，我们无法判断该语句的真假，进而非命题，但是一旦将 \( x \) 代入为某个具体的
对象，且该对象支持和 \( 3 \) 进行比较的话，则代入后的 \( x > 3 \) 就是个命题，我们给这种参数
化的命题一个定义：

#+begin_definition
*谓词（predicate）*
给定 \( E(x) \) 为一个带自由变量 \( x \) 的语句，假设将 \( x \) 代入为某类对象后，\( E(x) \) 成为命题了，
则我们称 \( E(x) \) 为一元谓词，简称谓词。谓词也称为性质。
#+end_definition

上述定义有点含糊，比如所谓某类的“类”的具体定义是什么，什么是对象，等等，这些属
于更深的对逻辑系统的研究，并不影响我们大部分的数学研究，故我们这里不展开，类可以
简单认为是日常意义上的集合，对象同理，可以认为是我们日常用语中具有宽泛意义的词
“对象”。

* 属于关系

给定 \( X \) 为一个类/集合，如果 \( x \) 是 \( X \) 中的一个元素，也就是说 \( x \) 被\( X \) 包含的话，则我
们说 \( x \) 属于 \( X \) ，记为 \( x \in X \) ，反之，如果 \( x \)不属于 \( X \)，则记为 \( x \notin X \) 。

* 通过谓词筛选类元素

给定类 \( X \) 和谓词 \( E(x) \) ，我们记 \( \{ x \in X; E(x) \} \) 为 \( X \) 中所有满足\( E(x) \) 的元素组成的类，
所谓的元素满足 \( E(x) \) ，指的是把该元素作为\( x \) 代入 \( E(x) \) 后，产生的命题为真命题。

我们直接断言 \( \{ x \in X; E(x) \} \) 这样的类存在，这属于集合论的内容，这里不进行展开。

* 量词

谓词 \( E(x) \) 有个不方便的地方，我们无法表达对 \( x \) 的限定，举个例子，我们可能想表达，
存在一个 \( x \in X \) 满足 \( E(x) \) ，也可能想表达任意 \( x \in X \) 均满足 \( E(x) \) ，我们当然可以像这
里这样通过自然语言进行描述，但是我们希望逻辑语言/符号中也有对应的等价物，为此，
我们引入量词（quantifier）。

首先是存在量词：

#+begin_definition
*存在量词（existential quantifier）*
\( \exists x \in X: E(x) \) 表示存在一个 \( x \in X \) 满足 \( E(x) \) ，其中符号 \( \exists \) 表示存在。

类似的， \( \exists! x \in X: E(x) \) 表示存在唯一的 \( x \in X \) 满足 \( E(x) \) ，这里的唯一指的是 \( X \) 中有
且仅有一个对象 \( x \) 满足 \( E(x) \) 。
#+end_definition

注意量词消除了自由变量，变量 \( x \) 不再是自由变量了，\( \exists x \in X: E(x) \) 本身就是一个命题，
不像谓词需要代入具体对象才会变成命题。

接着是全称量词：

#+begin_definition
*全称量词（universal quantifier）*
\( \forall x \in X: E(x) \) 表示所有 \( x \in X \) 均满足 \( E(x) \) ，其中符号 \( \forall \) 表示所有。
#+end_definition

* 定义

我们写 \( a := b \) 表示把 \( a \) 定义成 \( b \) ，可以认为 a 就是 \( b \) 的缩写/别名。

* 命题操作的性质

给定命题 \( A, B \) ，类 \( X, Y \) 以及谓词 \( E \) ，这时候通过对比以下等式两侧命题的真值表，容
易证明两个命题的真与假是等价的，即左边命题为真当且仅当右边命题为真，左边命题为假
当且仅当右边命题为假：

1. \( \neg \neg A := \neg (\neg A) = A \)
2. \( \neg (A \land B) = (\neg A) \lor (\neg B) \)
3. \( \neg (A \lor B) = (\neg A) \land (\neg B) \)
4. \( \neg (\forall x \in X: E(x)) = \exists x \in X: \neg E(x) \)
5. \( \neg (\exists x \in X: E(x)) = \forall x \in X: \neg E(x) \)


* 蕴含

我们经常会说“如果 \( A \) ，则 \( B \) ”，比如“如果 \( x > 3 \)，则 \( x^2 > 9 \)” ，这里我们的意思
是，如果命题 \( A \) 成立，则命题 \( B \) 一定也成立，但是如果 \( A \) 不成立，则我们不下任何结
论，特别的，我们此时不关心命题 \( B \) 的真假。

下面给正式定义：

#+begin_definition
*蕴含*
给定命题 \( A, B \) ，我们定义 \( (A \Rightarrow B) := (\neg A) \lor B \)
这里的 \( A \Rightarrow B \) 读作“如果 \( A \) ，则 \( B \) ”。
#+end_definition

读者可以验证，命题 \( A \Rightarrow B \) 为真满足上面提到的性质：如果命题 \( A \) 成立，则命题 \( B \) 一
定也成立，而如果 \( A \) 不成立，则我们不下任何结论，此时命题 \( A \Rightarrow B \) 直接视为成立。

在 \( A \Rightarrow B \) 中，我们称 \( B \) 为 \( A \) 的 *必要条件* ，因为 \( A \) 可以推出 \( B \) ，如果 \( B \) 是假的，
则推出 \( B \) 的 \( A \) 本身也一定是假的，所以 \( B \) 对于 \( A \) 来说是必要的，反之，我们称 \( A \)
是 \( B \) 的 *充分条件* ，因为 \( A \) 成立本身就足够推出 \( B \) 成立了，不需要额外的条件。

* 等价

#+begin_definition
*等价*
给定命题 \( A, B \) ，我们定义 \( (A \Leftrightarrow B) := (A \Rightarrow B) \land
(B \Rightarrow A) \) ，读作 \( A \) 等价于 \( B \) 。
#+end_definition

容易证明，如果 \( A \Leftrightarrow B \) ，则 \( A, B \) 同真假，这就是为什么我们称它们为等价的，即真假值
上的等价，即使两个命题从表面的描述来看，长得非常不一样，只要真假值等价，我们就认
为它们等价。

如果 \( A \Leftrightarrow B \) ，则按之前的说法， \( A \) 是 \( B \) 的充分必要条件，反之亦然，充分必要条件可
以缩写成充要条件。

* 逆否命题

对比真值表，容易证明以下的等价性：

\[ (A \Rightarrow B) \Leftrightarrow (\neg B \Rightarrow \neg A) \]

* 逆否证明法

我们知道 \( (A \Rightarrow B) \Leftrightarrow (\neg B \Rightarrow \neg A) \)，故如果想证明 \( A \Rightarrow B \) ，则可以尝试直接证明\( \neg B \Rightarrow \neg A \)
，因为有可能后者比前者更容易证明。

* 排中律

如果 \( A \) 是命题，则我们前面规定命题一定有真假，进而 \( A \) 和 \( \neg A \) 中有且仅有一个为真，
进而 \( A \lor \neg A \) 一定为真命题，这个称为排中律，也就是只有真假两种可能，不存在其他中间可能。

* 矛盾

#+begin_definition
*矛盾（contradiction）*
符号 \( \bot \) 表示恒假的命题。若从某个假设可以同时推出 \( B \) 和 \( \neg B \)，则称推出了矛盾，
因为这两个命题真假值相反，不可能同时为真。
#+end_definition

* 反证法

由排中律可以得到反证法：

#+begin_theorem
*反证法*
为了证明命题 \( A \) ，可以假设 \( \neg A \) 为真，并尝试推出矛盾 \( \bot \) ，而 \( \bot \) 恒假，
进而 \( \neg A \Rightarrow \dots \Rightarrow \bot \) 为假命题，特别地， \( \neg A \) 非真，由此得到 \( \neg\neg A = A \) 为真。
#+end_theorem
